### ISSUE TITLE
It's difficult to use https with omnifocus-rt and terminology is confusing

### ISSUE THREAD

**Issue by emory** [seattlerb/omnifocus-rt#1]
While setting up 'omnifocus-rt' I hit a couple of issues and possible bugs.
- The yaml generated by 'of sync' asks for an 'rt_url' but it actually doesn't want or expect a proper URI, just a hostname and path.
- Changing occurrences of 'http' to 'https' in 'rt.rb' may work with a valid certificate but
- self-signed certificates don't validate and I don't know how to best address it

Ordinarily I'd just bypass the check with:

```
 client.ssl_config.verify_mode = OpenSSL::SSL::VERIFY_NONE
 client.get(url)
```

but since rt.rb doesn't use the same method I don't know how to address or fix.  I'm willing to test any suggested fixes or work-arounds.

**Comment by zenspider** [comment]
Gah! Sorry this slipped through the cracks... `omnifocus-rt` isn't really my gem and nobody has been maintaining it as the original author no longer works at a place that uses RT.

First, please file all issues separately, so they can be handled and tracked separately (assuming they're unrelated).

The generated yaml (should be a separate issue) should probably actually take a URI. Not sure why it is only doing hostname and path. If you want to send in a PR for that, please do.

Next, self-signed certs don't validate because they're not really valid. They're meant for testing purposes, not security, per se. I'm not sure what the correct approach for that is either.

**Comment by zenspider** [comment]
No response. Closing.
